### ISSUE TITLE
Example feature request

### ISSUE THREAD

**Issue by andrewstech** [andrewstech/youtube-alexa-edition#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zhang563** [comment]
**Is your feature request related to a problem? Please describe.**
  Yes, I'm always frustrated when I could not play the exact video/song I want because voice control won't work perfectly when it comes to certain names and videos that are not in English.

**Describe the solution you'd like.**
  The ability for Alexa to play my youtube playlist, as well shuffle from my playlist.

**Describe alternatives you've considered**
  N/A
**Additional context**

  I don't know if my request is possible because I'm not an expert. What I thought was maybe the link to my playlists in the Voiceflow and Alexa might be able to access it?

**Comment by andrewstech** [comment]
I will get started on this soon

**Comment by E1cid** [comment]
Hi Andrew. Got it working And thank you for your efforts.

Is it possible to search straight from invocation, i.e. alexa ask youtube to play gorillaz the album. 
Also when you say play next it's a bit annoying that it asks, and you have to respond yes.

**Comment by andrewstech** [comment]
not currently but I should be able to add it

**Comment by E1cid** [comment]
i will look out for updates, once again thank you

**Comment by andrewstech** [comment]
> i will look out for updates, once again thank you

This is now integrated into the published code.

update it via this method:  https://youtu.be/5k9OGbeek28?t=598
