### ISSUE TITLE
Skill recognized but doesn't work

### ISSUE THREAD

**Issue by jradium1** [andrewstech/youtube-alexa-edition#44]
Thanks Paul and Andrew for the hard work and nice presentation. However, it still doesn't work for me. If I use the open command, it says "welcome to ...." If I say "Alexa, ask ... to play ...", it says "welcome to ... playing ..." but nothing happens. Please advise.

I would like to mention also that the project flow looks different (and smaller) when I open the code link (https://download.andrewstech.me/youtube-skill-v3) in my voiceflow platform.

Here is what I find when I look into Activity in the Alexa app:
**Skill response was marked as failure
Youtube reader
Request Identifier: zmz1.echo-api.request.d8b57697-be1c-4437-a533-cde642c00b19
The skill responded with 503 HTTP status code
Voice feedback
Alexa heard: "ask youtube reader to play michael jackson"**

**Comment by jradium1** [comment]
I would like to add that I get the same behavior if I change the invocation phase to, for example, my streamer.

**Comment by andrewstech** [comment]
Hi the error you received is a 503 issue which means the server is
unavailable. This is likely caused by voiceflow during there recent
upgrade. I would try heading to voiceflow open your project and click the
upload button again.

The voiceflow status can be found here: https://status.voiceflow.com/

The skill status can be found at: https://skills-status.andrewstech.me

Hope this helps
-Andrew

**Comment by andrewstech** [comment]
This issue will be patched in the new version of alpha-vi upon release.

**Comment by andrewstech** [comment]
Hope that helps
